/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_gnubgAPI */

#ifndef _Included_com_example_testndk_gnubgAPI
#define _Included_com_example_testndk_gnubgAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndk_gnubgAPI
 * Method:    RollDice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_RollDice
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
