/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_gnubgAPI */

#ifndef _Included_com_example_testndk_gnubgAPI
#define _Included_com_example_testndk_gnubgAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndk_gnubgAPI
 * Method:    RollDice
 * Signature: ([II)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_RollDice
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_testndk_gnubgAPI
 * Method:    InitializeEnvironment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_InitializeEnvironment
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testndk_gnubgAPI
 * Method:    SetIALevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetIALevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
