/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_gnubgAPI */

#ifndef _Included_com_example_testndk_gnubgAPI
#define _Included_com_example_testndk_gnubgAPI
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_InitializeEnvironment
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetAILevel
  (JNIEnv *, jclass, jint);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_RollDice
  (JNIEnv *, jclass, jintArray);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetBoard
  (JNIEnv *, jclass, jintArray, jintArray);


JNIEXPORT jint JNICALL Java_com_example_testndk_gnubgAPI_AcceptResign
  (JNIEnv *, jclass, jint);


JNIEXPORT jint JNICALL Java_com_example_testndk_gnubgAPI_AcceptDouble
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_UpdateMSCubeInfo
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_EvaluateBestMove
  (JNIEnv *, jclass, jintArray, jintArray);


JNIEXPORT jint JNICALL Java_com_example_testndk_gnubgAPI_AskForResignation
  (JNIEnv *, jclass);


JNIEXPORT jint JNICALL Java_com_example_testndk_gnubgAPI_AskForDoubling
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetMatchScore
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetGameTurn
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_SetMatchTo
  (JNIEnv *, jclass, jint);


//ONLY FOR TEST PURPOSE
JNIEXPORT void JNICALL Java_com_example_testndk_gnubgAPI_TestAll
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
